title: Kefan Yu 于 可凡
url: "https://huangtubaye233.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Thanks for the page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "CV_Kefan_Yu.pdf"
 - name: "Contact"
   link: "contact"
